### ISSUE TITLE
Navigation QA

### ISSUE THREAD

**Issue by vickibrown** [thinkshout/thinkshout#818]
**Desktop**
- [x] Add hover/focus states to the main nav text. The text should turn hex #BF450D at hover/focus

**Mobile**
_This has more fixes._
- [x] Change hamburger nav color to hex 242424
- [x] Reduce the size of the logo by 30%. Retain the height of the white bar and vertically center the logo within the bar.
- [x] The hamburger icon is a link without an href, so it's not showing up in the tab order. Update it to be a button or a span with `role="button"`, `tabindex="0"`. This is done when I can tab to the hamburger button, hit return and open the mobile menu. The same goes for the close button on the mobile menu. 
<img width="594" alt="Screen Shot 2020-05-05 at 7 16 54 PM" src="https://user-images.githubusercontent.com/19519395/81132987-1d747000-8f05-11ea-8b5a-ecd24d31f0f7.png">
<img width="410" alt="Screen Shot 2020-05-05 at 7 14 51 PM" src="https://user-images.githubusercontent.com/19519395/81132991-1ea59d00-8f05-11ea-8fac-0eb1ee748060.png">

**When menu is expanded**
- [x] Change X for active hamburger nav to hex 242424 also
- [x] Change white background to 100% opacity
- [x] add 50% more padding before navigation text
- [x] Change text links to hex 242424
- [x] Reduce size of text by 25%
- [x] add 50% line height between text items
<img width="487" alt="Screen Shot 2020-05-05 at 10 28 56 AM" src="https://user-images.githubusercontent.com/21184833/81099053-22163580-8ebf-11ea-8f63-88d2cba42adb.png">

**Comment by komejo** [comment]
Ready for review on https://a11y-2020--thinkshout.netlify.app/

**Comment by vickibrown** [comment]
@komejo this looks great, just a few things that aren't looking fixed:
- [ ]  add 50% more padding before navigation text
- [ ]  Change text links to hex 242424 (these should match the hamburger, so check both)
- [ ]  add 50% line height between text items
- [ ] Also something new, when I close the menu the x should get replace the hamburger icon again, it's currently staying an x and then it's backwards when I click it again

![IMG_6999](https://user-images.githubusercontent.com/21184833/82352333-aa620380-99b2-11ea-9fe4-4bc64a3b01ca.PNG)
![IMG_7001](https://user-images.githubusercontent.com/21184833/82352454-dda49280-99b2-11ea-9e8d-20f88927f3cd.PNG)

**Comment by JulesKhong** [comment]
For the hamburger menu, there's a "Very small text" error on WAVE. To fix it you could use an aria-label="menu" on `.mobile-menu-icon`, or wrap the word Menu in a span.visually-hidden, and add the CSS style 

```
.visually-hidden {
  position: absolute !important;
  clip: rect(1px, 1px, 1px, 1px);
  overflow: hidden;
  height: 1px;
  width: 1px;
  word-wrap: normal;
}```

[reference](https://www.drupal.org/docs/accessibility/hide-content-properly)

**Comment by JulesKhong** [comment]
- [ ] Update the mobile menu button so the aria-label is "open mobile menu" or "close mobile menu" depending on whether it's open or closed. An example of this is on https://realizingdemocracy.org/

**Comment by komejo** [comment]
All feedback applied and ready for final QA on https://a11y-2020--thinkshout.netlify.app/

Bonus: learned how to implement Accessible inline SVGs!

**Comment by JulesKhong** [comment]
One fix needed [in this comment above](https://github.com/thinkshout/thinkshout/issues/818#issuecomment-635621817), everything else looked good.

**Comment by komejo** [comment]
Ahhh, I didn't realize that I would also need to remove the text and the font-size declaration - done, and verified with VoiceOver and Wave.

**Comment by vickibrown** [comment]
@komejo Looks good from a design standpoint.
