### ISSUE TITLE
Person detail page QA

### ISSUE THREAD

**Issue by vickibrown** [thinkshout/thinkshout#824]
https://thinkshout.com/team/kaylan/

- [x] Change title to hex #D24C0F
- [x] Change social icons to hex F06D2F
- [x] add hover/focus to social icons of hex F38958

**Comment by komejo** [comment]
Ready for review on https://a11y-2020--thinkshout.netlify.app/team/joe/

**Comment by vickibrown** [comment]
@komejo looks good, just one thing.
- [ ] Change the title to hex D24C0F and make it Title case (not all caps) and Gotham Medium.

**Comment by JulesKhong** [comment]
- [ ] Social media icons need accessible labels. They should reference the person's account, so "Joe's Twitter", or "Follow Joe on Twitter."
<img width="202" alt="Screen Shot 2020-05-29 at 4 45 59 PM" src="https://user-images.githubusercontent.com/19519395/83313628-ee7fb000-a1cb-11ea-92ff-91aa6ce87484.png">

**Comment by komejo** [comment]
All feedback applied and ready for final QA on https://a11y-2020--thinkshout.netlify.app/team/joe/

**Comment by JulesKhong** [comment]
Approved from an a11y QA perspective 💯

**Comment by vickibrown** [comment]
@komejo looks good!
