### ISSUE TITLE
Careers page QA

### ISSUE THREAD

**Issue by vickibrown** [thinkshout/thinkshout#833]
This page needs help https://thinkshout.com/careers/

- [x] The image is SUPER awkward, can we have a central focal point? Otherwise contact @vickibrown for a cropped image.
- [x] The intro text just below the hero edits: remove italics, make it 18 pixels with 24 pixels of line height (would love it to match the teaser text in these listings https://a11y-2020--thinkshout.netlify.app/blog/
- [x] Job listing needs a hover/focus state, add underline for that
- [x] reduce padding between title and location by 50%

**In the gray box:**
- [x] change the background color to hex ##F0F0F0
- [x] Change the link color to #BF450D
- [x] add hover/focus state to the link so it underlines

**Comment by komejo** [comment]
Done and ready for review: https://a11y-2020--thinkshout.netlify.app/careers/

**Comment by JulesKhong** [comment]
- [ ] Careers page needs an H1
